# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

cirrus_wm_adsp-objs = wm_adsp.o
obj-m += cirrus_wm_adsp.o

cirrus_cs35l41-objs = cs35l41.o cs35l41-tables.o
obj-m += cirrus_cs35l41.o
cirrus_cs35l41-objs += cs35l41-i2c.o
